### ISSUE TITLE
stops working when upgrading from angular 1.3.0-build.2991+sha.9025113 to 1.3.0-beta.7

### ISSUE THREAD

**Issue by thomasvs** [g00fy-/angular-datepicker#58]
I was using datepicker as follows:

&lt;div class="dropdown-menu" ng-click="update()">
          &lt;div date-picker="due" max-view="year" min-view="date">
          &lt;/div>
        &lt;/div>

In both versions it works if $scope.due is set to a value.

If it is set to undefined, and the version is 1.3.0-beta.7 (the next release candidate) it stops working, and generates this exception:

TypeError: undefined is not a function
    at http://0.0.0.0:9001/bower_components/angular/angular.js:22066:55
    at publicLinkFn (http://0.0.0.0:9001/bower_components/angular/angular.js:6264:29)
    at boundTranscludeFn (http://0.0.0.0:9001/bower_components/angular/angular.js:6406:21)
    at controllersBoundTransclude (http://0.0.0.0:9001/bower_components/angular/angular.js:7047:18)
    at http://0.0.0.0:9001/bower_components/angular/angular.js:22064:27
    at processQueue (http://0.0.0.0:9001/bower_components/angular/angular.js:12018:27)
    at http://0.0.0.0:9001/bower_components/angular/angular.js:12034:27
    at Scope.$eval (http://0.0.0.0:9001/bower_components/angular/angular.js:13202:28)
    at Scope.$digest (http://0.0.0.0:9001/bower_components/angular/angular.js:13014:31)
    at Scope.$delegate.**proto**.$digest (<anonymous>:844:31)
